package gamebox;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

import pacMan.PacmanFrame;
import snake.SnakeFrame;
import snake.SnakeMenuFrame;
import tictactoe.TicTacToeMenuFrame;

public class ArcadeMenu extends javax.swing.JFrame implements ActionListener
{

        /**
        * Creates new form MainMenuFrame
        */
        public ArcadeMenu() {
            initComponents();
        }

        /**
        * This method is called from within the constructor to initialize the form.
        * WARNING: Do NOT modify this code. The content of this method is always
        * regenerated by the Form Editor.
        */
        @SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("TicTacToe");
        jButton1.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(71, 23));

        jButton2.setText("Pac-Man");
        jButton2.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(71, 23));

        jButton3.setText("Snake");
        jButton3.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(71, 23));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gamebox/arcadeTitle.jpg"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(148, 148, 148))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(13, 13, 13)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jButton3.addActionListener(this);
        pack();
    }// </editor-fold>                        

 

     // Variables declaration - do not modify                     
        private javax.swing.JButton jButton1;
        private javax.swing.JButton jButton2;
        private javax.swing.JButton jButton3;
        private javax.swing.JLabel jLabel1;
         // End of variables declaration                   

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getActionCommand().equals("TicTacToe")){
            JFrame game = new TicTacToeMenuFrame();
            game.getContentPane().setBackground(new Color(255,255,255));
            game.setResizable(false);
            game.setTitle("Tic Tac Toe Menu");
            game.setSize(400, 400);
            game.setLocationRelativeTo(null);
            game.setVisible(true);
        }
        
        if(e.getActionCommand().equals("Pac-Man")){
           JFrame game = new PacmanFrame();
           
        }
        
        if(e.getActionCommand().equals("Snake")){
            SnakeMenuFrame game = new SnakeMenuFrame();
            game.getContentPane().setBackground(new Color(0,0,0));
            game.setResizable(false);
            game.setTitle("Snake Menu");
            game.setSize(400, 400);
            game.setLocationRelativeTo(null);
            game.setVisible(true);
            
        }
      }
    
    
 }
