package tictactoe;
import java.awt.*;
import java.awt.event.*;
import javax.swing.JFrame;

public class TicTacToeMenuFrame extends javax.swing.JFrame implements  ActionListener{

    /**
     * Creates new form MainMenuFrame
     */
    public TicTacToeMenuFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();

        
        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setText("Normal");
        jButton1.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(71, 23));

        jButton2.setText("Ultimate");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/mainMenu.gif"))); // NOI18N

        jButton3.setText("Corn");
        jButton3.setMaximumSize(new java.awt.Dimension(71, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(71, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(71, 23));
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(25, 25, 25)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        pack();
    }// </editor-fold>                        
     
  
 

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration         

    @Override
    public void actionPerformed(ActionEvent e) {
       if(e.getActionCommand().equals("Normal"))
       {
           JFrame game = new TicTacToeFrame();
           game.setTitle("Tic Tac Toe");
           game.setSize(600, 600);
           game.setLocationRelativeTo(null);
           game.setVisible(true);
       }
       
       if(e.getActionCommand().equals("Ultimate"))
       {
           JFrame game = new Ultimate_TTT();
           game.setTitle(" Ultimate Tic Tac Toe");
           game.setSize(600, 600);
           game.setLocationRelativeTo(null);
           game.setVisible(true);
       }
       
    }

    
}
